name: Loveme
version: '${project.version}'
main: loveme.loveme.Loveme
api-version: 1.18
commands:
  noteblock:
    description: Toggles player can place noteblock.
    usage: /noteblock
    permission: loveme.admin
    permission-message: You do not have permission.