name: Loveme
version: '${project.version}'
main: loveme.loveme.Loveme
api-version: 1.18
commands:
  scanmob:
    description: Scanning mob.
    usage: /scanmob
    aliases: [mobscan, ms, scmob]
    permission: loveme.admin
    permission-message: You do not have permission.